apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/*
        echo "Cleanup complete!"
- name: nose-test
  image: python:3.10
  script: |
    #!/bin/bash
    echo "Running Nose tests..."
    pip install nose
    nosetests tests/
    echo "Nose tests completed!"

